/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolog;

//import java.util.HashSet;
import java.util.Hashtable;
import java.util.Map;
import org.jpl7.*;

/**
 *
 * @author jose
 */
public class frame extends javax.swing.JFrame {
        
    /**
     * Creates new form frame
     */
    public frame() {
        initComponents();
        
        try
        {
            Query consulta = new Query(
                    new Compound(
                        "consult",
                        new Term [] {new Atom("waifus.pl")}
                    )
                    
            );
            System.out.println( "consult " + (consulta.hasSolution() ? "succeeded" : "failed"));
            
            String var = "X";
            String atom1 = "light";
            String atom2 = "pink";
            String atom3 = "long";
            Query q1;
            q1 = new Query(
                    new Compound(
                            "hair",
                            new Term [] {new Variable(var),new Atom(atom1),new Atom(atom2),new Atom(atom3)}
                    )
            );
            Map<String, Term> solution;
            System.out.println(q1.hasSolution());
            while (q1.hasMoreSolutions())
            {
                solution = q1.nextSolution();
                System.out.println("X = " + solution.get(var));
            }
            /*String qr = "consult('family.pl')";
            Query con;
            con = new Query(qr);
            System.out.println(qr + " "+ (con.hasMoreSolutions()?"GOOD":"FALLADO"));
            String A = jTextField3.getText();
            String B = jTextField2.getText();
            String C = jTextField4.getText();
            String D = jTextField1.getText();
            System.out.println(A);   
            System.out.println(B);   
            System.out.println(C);   
            System.out.println(D);
            Query q4;
            q4 = new Query(
                    new Compound( 
                            "parent",
                            new Term[] {new Variable("X"),new Atom("bob")}
                    )
            );
            Map<String, Term> solution;
            while (q4.hasMoreSolutions()) {
                solution = q4.nextSolution();
                System.out.println("X = " + solution.get("X"));
            }
            /////////////
            Query q5;
            q5 = new Query(
                    new Compound( 
                            "parent",
                            new Term[] {new Atom("tom"),new Atom("bob")}
                    )
            );
            System.out.println("parent(tom,bob) is "+q5.hasSolution());
            */
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
